### ISSUE TITLE
CSS to Sass.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/react-app-mahabharath#9]
Please change carefully and efficiently. Only if it is possible, else leave it.

**Comment by RShalman** [comment]
I'll take it

**Comment by Abhiramborige** [comment]
Yup, best of luck, please be careful, please don't change the appearance of the web app.

**Comment by RShalman** [comment]
> Yup, best of luck, please be careful, please don't change the appearance of the web app.

Don't worry)
Already fixed this in [this PR](https://github.com/Abhiramborige/react-app-mahabharath/pull/10)

**Comment by Abhiramborige** [comment]
could you please send the screenshots of all 
1. homepage
2. connect page
3. about page
4. any character after clicking
Please dude, don't feel bad for that but please.

**Comment by RShalman** [comment]
![image](https://user-images.githubusercontent.com/28634001/135726304-87be397e-dccb-4a96-aa31-b1c0d10d5d11.png)
![image](https://user-images.githubusercontent.com/28634001/135726312-2d96645d-2838-40ae-aba4-a9c29cd45606.png)
![image](https://user-images.githubusercontent.com/28634001/135726331-8177ca08-7ad3-4774-9836-91fc8e513394.png)

There are some issues with data fetch I guess because I get smth. like this on character click.
![image](https://user-images.githubusercontent.com/28634001/135726355-799a460f-de86-425a-826e-53124fa2cc92.png)

**Comment by RShalman** [comment]
Keep in mind that I've added **sass** dep for transpiling all scss files into casual css. So you need to run ``` npm i ``` before running my branch.

**Comment by Abhiramborige** [comment]
Yup, thanks for that.

**Comment by Abhiramborige** [comment]
Hey, could you please fix this.

**Comment by Abhiramborige** [comment]
![image](https://user-images.githubusercontent.com/54103320/135740918-d02f4845-6e51-4417-a713-5ecd1f956ac2.png)

**Comment by Abhiramborige** [comment]
![image](https://user-images.githubusercontent.com/54103320/135740926-e8e21ce7-bf3d-4df1-9f50-e391b60e7bb9.png)

**Comment by Abhiramborige** [comment]
Both div containers are named with class "flex-info", but the other one is not getting the css properties.

**Comment by Abhiramborige** [comment]
Could you please fix this small issue

**Comment by RShalman** [comment]
Sure, but this problem appears because you keep those files separately from your components and may reuse them in a huge variety of ways. I would suggest to keep styles close to a particular components or set of components. 

Will make s PR for the fix.

**Comment by Abhiramborige** [comment]
Yup, thanks for suggestions. waiting..
